apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
data:
  config.toml: |
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
       address = ":80"
      [entryPoints.https]
       address = ":443"
    [rest]
      entryPoint = "traefik"
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
        name: traefik
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: configmap
          configMap:
            name: traefik
      containers:
      - image: traefik
        name: traefik
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 8080
        volumeMounts:
          - name: configmap
            mountPath: /config
        args:
        - --configFile=/config/config.toml
---
kind: Service
apiVersion: v1
metadata:
  name: traefik
spec:
  selector:
    app: traefik
  externalIPs:
    - <YOUR IP HERE>
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 8080
      name: admin